/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\rpw.sqlite\manifest" -prefix "RPW_SQLITE_"

#pragma once

#ifndef RPW_SQLITE_MANIFEST_DATE
#define RPW_SQLITE_MANIFEST_DATE "2011-06-21 20:45:30.020"
#endif
