/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\rpw.sqlite\manifest.uuid" -prefix "RPW_SQLITE_"

#pragma once

#ifndef RPW_SQLITE_MANIFEST_UUID
#define RPW_SQLITE_MANIFEST_UUID "7b8badfe404a470867b0a3a331f85271d58e7992"
#endif

#ifndef RPW_SQLITE_MANIFEST_VERSION
#define RPW_SQLITE_MANIFEST_VERSION "7b8badfe40"
#endif
